// <auto-generated />
using AlbumCollection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AlbumCollection.Migrations
{
    [DbContext(typeof(MusicContext))]
    [Migration("20190310014827_AddedImages")]
    partial class AddedImages
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AlbumCollection.Models.Album", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArtistName");

                    b.Property<string>("ImgPath");

                    b.Property<string>("Name");

                    b.HasKey("AlbumId");

                    b.ToTable("Albums");

                    b.HasData(
                        new { AlbumId = 1, ArtistName = "Lou Reed", ImgPath = "/Images/Transformer.jpg", Name = "Transformer" },
                        new { AlbumId = 2, ArtistName = "Opeth", ImgPath = "/Images/Opeth.jpg", Name = "Ghost Reveries" },
                        new { AlbumId = 3, ArtistName = "Creedence Clearwater Revival", ImgPath = "/Images/CCR.jpg", Name = "Green River" }
                    );
                });

            modelBuilder.Entity("AlbumCollection.Models.Song", b =>
                {
                    b.Property<int>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlbumId");

                    b.Property<string>("Name");

                    b.HasKey("SongId");

                    b.HasIndex("AlbumId");

                    b.ToTable("Songs");

                    b.HasData(
                        new { SongId = 1, AlbumId = 1, Name = "Vicious" },
                        new { SongId = 2, AlbumId = 1, Name = "Andy's Chest" },
                        new { SongId = 3, AlbumId = 1, Name = "Perfect Day" },
                        new { SongId = 4, AlbumId = 1, Name = "Hangin' Round" },
                        new { SongId = 5, AlbumId = 1, Name = "Walk on the Wild Side" },
                        new { SongId = 6, AlbumId = 1, Name = "Make Up" },
                        new { SongId = 7, AlbumId = 1, Name = "Satellite of Love" },
                        new { SongId = 8, AlbumId = 1, Name = "Wagon Wheel" },
                        new { SongId = 9, AlbumId = 1, Name = "New York Telephone Conversation" },
                        new { SongId = 10, AlbumId = 1, Name = "I'm So Free" },
                        new { SongId = 11, AlbumId = 1, Name = "Goodnight Ladies" },
                        new { SongId = 12, AlbumId = 2, Name = "Ghost of Perdition" },
                        new { SongId = 13, AlbumId = 2, Name = "The Baying of the Hounds" },
                        new { SongId = 14, AlbumId = 2, Name = "Beneath the Mire" },
                        new { SongId = 15, AlbumId = 2, Name = "Atonement" },
                        new { SongId = 16, AlbumId = 2, Name = "Reverie/Harlequin Forest" },
                        new { SongId = 17, AlbumId = 2, Name = "Hours of Wealth" },
                        new { SongId = 18, AlbumId = 2, Name = "The Grand Conjuration" },
                        new { SongId = 19, AlbumId = 2, Name = "Isolation Years" },
                        new { SongId = 20, AlbumId = 3, Name = "Green River" },
                        new { SongId = 21, AlbumId = 3, Name = "Commotion" },
                        new { SongId = 22, AlbumId = 3, Name = "Tombstone Shadow" },
                        new { SongId = 23, AlbumId = 3, Name = "Wrote a Song for Everyone" },
                        new { SongId = 24, AlbumId = 3, Name = "Bad Moon Rising" },
                        new { SongId = 25, AlbumId = 3, Name = "Lodi" },
                        new { SongId = 26, AlbumId = 3, Name = "Cross-Tie Walker" },
                        new { SongId = 27, AlbumId = 3, Name = "Sinister Purpose" },
                        new { SongId = 28, AlbumId = 3, Name = "The Night Time Is the Right Time" }
                    );
                });

            modelBuilder.Entity("AlbumCollection.Models.Song", b =>
                {
                    b.HasOne("AlbumCollection.Models.Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
